server:
  port: 9090
  max-http-header-size: 65536
  max-http-request-header-size: 65536
  tomcat:
    max-http-request-header-size: 65536
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/x-protobuf
    min-response-size: 1024

spring:
  application:
    name: ftth-gis-core
  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://localhost:5432/ftth_gis
    username: postgres
    password: ${DB_PASSWORD:9kFw2mSp7r9D8zXpQ}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.format_sql]": false
      "jakarta.persistence.sharedCache.mode": ENABLE_SELECTIVE
      "hibernate.cache.use_second_level_cache": true
      "hibernate.cache.use_query_cache": true
      "hibernate.cache.region.factory_class": org.redisson.hibernate.RedissonRegionFactory
      "hibernate.cache.redisson.config": classpath:redisson.yaml

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  data:
    redis:
      enabled: true # Set to false if Redis is not running
      host: 127.0.0.1
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-gis.k2net.id/realms/ftth-realm
          jwk-set-uri: http://localhost:8081/realms/ftth-realm/protocol/openid-connect/certs

# Keycloak Admin Configuration
keycloak:
  server-url: https://auth-gis.k2net.id
  internal-url: http://localhost:8081
  realm: master
  # Service Account for Backend to manage everything (from master realm)
  client-id: ftth-gis-admin
  client-secret: 5eUIWOk9GmUxX0nSwDSLmOHVFFY2JRk8
  grant-type: client_credentials

# Custom Config for App Security
# Note: 'app' is a custom property. The IDE warning 'Unknown property' is safe to ignore
# as it is not part of the internal Spring Boot schema.
app:
  seeder:
    enabled: false # Data sudah sinkron. Set true HANYA jika ingin reset ulang semua aset.
  frontend-url: ${FRONTEND_URL:localhost:3000}
  security:
    keycloak:
      provision-client-id: ${AUTH_KEYCLOAK_ID:ftth-gis-frontend}
      provision-client-secret: ${AUTH_KEYCLOAK_SECRET:6b2eKluzW7eVxg5Fapx1p3e2O6b91oFs}
    cors:
      allowed-origins: "http://localhost:3000,http://127.0.0.1:3000,http://192.168.40.11:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

logging:
  level:
    "[org.hibernate.SQL]": WARN
    "[org.hibernate.type.descriptor.sql.BasicBinder]": WARN
    "[org.springframework.security]": WARN
  file:
    name: logs/ftth-backend.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: when_authorized

