http:
  routers:
    sms-webhook-router:
      rule: "(Host(`gis.kdua.net`) || HostRegexp(`^[a-z0-9-]+\\.gis\\.kdua\\.net$`) || HostRegexp(`^[a-z0-9-]+-gis\\.kdua\\.net$`)) && PathPrefix(`/webhooks/sms`)"
      entrypoints:
        - websecure
      tls: {}
      service: sms-webhook-service
      priority: 15

  middlewares:
    secHeaders:
      headers:
        sslRedirect: true
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "strict-origin-when-cross-origin"

  services:
    sms-webhook-service:
      loadBalancer:
        servers:
          - url: "http://ftth-notification-gateway:5001"
