http:
  routers:
    poller-router:
      rule: "(Host(`gis.kdua.net`) || HostRegexp(`^[a-z0-9-]+\\.gis\\.kdua\\.net$`) || HostRegexp(`^[a-z0-9-]+-gis\\.kdua\\.net$`)) && PathPrefix(`/poller/`)"
      entrypoints:
        - websecure
      tls: {}
      middlewares:
        - poller-stripprefix
      service: poller-service
      priority: 15

    sms-webhook-router:
      rule: "(Host(`gis.kdua.net`) || HostRegexp(`^[a-z0-9-]+\\.gis\\.kdua\\.net$`) || HostRegexp(`^[a-z0-9-]+-gis\\.kdua\\.net$`)) && PathPrefix(`/webhooks/sms`)"
      entrypoints:
        - websecure
      tls: {}
      service: sms-webhook-service
      priority: 15

  middlewares:
    poller-stripprefix:
      stripPrefix:
        prefixes:
          - "/poller"

  services:
    poller-service:
      loadBalancer:
        servers:
          - url: "http://ftth-poller:5010"
    sms-webhook-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5001"
