package com.company.ftthgis.api.system;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;

import java.io.IOException;
import java.io.InputStream;
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryMXBean;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.Properties;

/**
 * REST Controller to expose DevOps-related statistics for the admin dashboard.
 * Provides information about: Git branch/commit, Flyway migration status,
 * server compute resources, and last database backup timestamp.
 */
@RestController
@RequestMapping("/api/v1/system/devops-stats")
@RequiredArgsConstructor
@Slf4j
@PreAuthorize("isAuthenticated()")
public class DevOpsStatsController {

    private final JdbcTemplate jdbcTemplate;

    @Value("${app.gateway.storage-url:http://ftth-storage-gateway:5004}")
    private String storageGatewayUrl;

    @Value("${app.gateway.token:}")
    private String gatewayToken;

    private final RestTemplate restTemplate = new RestTemplate();

    private BucketStats fetchBucketStats(String bucketName) {
        try {
            String url = storageGatewayUrl + "/api/v1/bucket-stats?bucket=" + bucketName;
            HttpHeaders headers = new HttpHeaders();
            headers.set("X-Gateway-Token", gatewayToken);
            HttpEntity<?> entity = new HttpEntity<>(headers);
            ResponseEntity<BucketStats> response = restTemplate.exchange(
                    url,
                    HttpMethod.GET,
                    entity,
                    BucketStats.class
            );
            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                return response.getBody();
            }
        } catch (Exception e) {
            log.warn("Failed to fetch bucket stats for bucket '{}' from storage-gateway: {}", bucketName, e.getMessage());
        }
        return new BucketStats(bucketName, 0L, 0L); // fallback
    }

    @Value("${app.devops.github.frontend-repo:https://github.com/user/front_springboot_ftth_gis}")
    private String frontendRepoUrl;

    @Value("${app.devops.github.backend-repo:https://github.com/user/back_springboot_ftth_gis}")
    private String backendRepoUrl;

    @Value("${app.devops.backup.log-path:/var/backups/postgresql/last_backup.log}")
    private String backupLogPath;

    @GetMapping
    public ResponseEntity<DevOpsStatsResponse> getDevOpsStats() {
        try {
            // 1. Load Git properties (generated by git-commit-id-maven-plugin at compile time)
            GitInfo gitInfo = loadGitInfo();

            // 2. Query Flyway migration history for the latest successful migration
            MigrationInfo migrationInfo = loadMigrationInfo();

            // 3. Gather compute resources from JVM runtime
            ComputeInfo computeInfo = loadComputeInfo();

            // 4. Determine last backup timestamp
            BackupInfo backupInfo = loadBackupInfo();

            // 5. Check database settings for custom GitHub repository
            String dbGithubSetting = getGithubRepoFromSettings();
            String repo = parseRepoFromJson(dbGithubSetting);
            String frontendUrl = (repo != null && !repo.isEmpty()) ? "https://github.com/" + repo : frontendRepoUrl;
            String backendUrl = (repo != null && !repo.isEmpty()) ? "https://github.com/" + repo : backendRepoUrl;

            DevOpsStatsResponse response = new DevOpsStatsResponse(
                    gitInfo,
                    migrationInfo,
                    computeInfo,
                    backupInfo,
                    new GithubInfo(frontendUrl, backendUrl)
            );

            return ResponseEntity.ok(response);
        } catch (Exception e) {
            log.error("Failed to load DevOps stats: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError().build();
        }
    }

    private String getGithubRepoFromSettings() {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT config_value FROM system_settings WHERE config_key = 'github_integration'",
                    String.class
            );
        } catch (Exception e) {
            return null;
        }
    }

    private String parseRepoFromJson(String json) {
        if (json == null || !json.contains("\"repo\":\"")) {
            return null;
        }
        try {
            int start = json.indexOf("\"repo\":\"") + 8;
            int end = json.indexOf("\"", start);
            if (start > 7 && end > start) {
                return json.substring(start, end);
            }
        } catch (Exception e) {
            // ignore
        }
        return null;
    }

    /**
     * Reads git.properties from classpath. This file is generated by
     * git-commit-id-maven-plugin during the Maven build phase.
     */
    private GitInfo loadGitInfo() {
        Properties gitProps = new Properties();
        try (InputStream is = getClass().getClassLoader().getResourceAsStream("git.properties")) {
            if (is != null) {
                gitProps.load(is);
            } else {
                log.warn("git.properties not found on classpath. Git info will use fallback values.");
            }
        } catch (IOException e) {
            log.warn("Could not read git.properties: {}", e.getMessage());
        }

        return new GitInfo(
                gitProps.getProperty("git.branch", "main"),
                gitProps.getProperty("git.commit.id.abbrev", "unknown"),
                gitProps.getProperty("git.commit.id.full", "unknown"),
                gitProps.getProperty("git.commit.message.short", "N/A"),
                gitProps.getProperty("git.commit.time", "N/A"),
                gitProps.getProperty("git.commit.user.name", "N/A")
        );
    }

    /**
     * Queries the Flyway schema history table for the most recently applied migration.
     * Uses parameterized query via JdbcTemplate (safe from SQL injection).
     */
    private MigrationInfo loadMigrationInfo() {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT version, description, installed_on, success " +
                    "FROM flyway_schema_history " +
                    "WHERE success = true " +
                    "ORDER BY installed_rank DESC LIMIT 1",
                    (rs, rowNum) -> new MigrationInfo(
                            rs.getString("version"),
                            rs.getString("description"),
                            rs.getTimestamp("installed_on") != null
                                    ? rs.getTimestamp("installed_on").toLocalDateTime()
                                            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                    : "N/A",
                            rs.getBoolean("success")
                    )
            );
        } catch (Exception e) {
            log.warn("Could not query flyway_schema_history: {}", e.getMessage());
            return new MigrationInfo("N/A", "Unable to retrieve", "N/A", false);
        }
    }

    /**
     * Reads JVM runtime information for compute resource monitoring.
     * This avoids needing external system libraries.
     */
    private ComputeInfo loadComputeInfo() {
        Runtime runtime = Runtime.getRuntime();
        int cpuCores = runtime.availableProcessors();
        long maxMemoryMb = runtime.maxMemory() / (1024 * 1024);
        long usedMemoryMb = (runtime.totalMemory() - runtime.freeMemory()) / (1024 * 1024);
        long totalMemoryMb = runtime.totalMemory() / (1024 * 1024);

        MemoryMXBean memoryMXBean = ManagementFactory.getMemoryMXBean();
        long heapUsedMb = memoryMXBean.getHeapMemoryUsage().getUsed() / (1024 * 1024);
        long heapMaxMb = memoryMXBean.getHeapMemoryUsage().getMax() / (1024 * 1024);
        long nonHeapUsedMb = memoryMXBean.getNonHeapMemoryUsage().getUsed() / (1024 * 1024);

        // Determine VM tier label based on CPU/RAM
        String tier;
        if (cpuCores <= 1 && maxMemoryMb <= 1024) {
            tier = "NANO";
        } else if (cpuCores <= 2 && maxMemoryMb <= 2048) {
            tier = "MICRO";
        } else if (cpuCores <= 2 && maxMemoryMb <= 4096) {
            tier = "SMALL";
        } else if (cpuCores <= 4 && maxMemoryMb <= 8192) {
            tier = "MEDIUM";
        } else {
            tier = "LARGE";
        }

        return new ComputeInfo(
                tier,
                cpuCores,
                maxMemoryMb,
                usedMemoryMb,
                totalMemoryMb,
                System.getProperty("java.version"),
                System.getProperty("os.name") + " " + System.getProperty("os.arch"),
                heapUsedMb,
                nonHeapUsedMb,
                heapMaxMb
        );
    }

    /**
     * Attempts to read the last backup timestamp from a log file.
     * If the log file is not available, returns a fallback indicating backup status is unknown.
     */
    private BackupInfo loadBackupInfo() {
        BucketStats dbStats = fetchBucketStats("db-backups");
        BucketStats codeStats = fetchBucketStats("code-backups");
        BucketStats dockerStats = fetchBucketStats("docker-backups");

        try {
            return jdbcTemplate.queryForObject(
                    "SELECT backup_time, status, success, minio_status, minio_sync_time, nextcloud_status, nextcloud_sync_time " +
                    "FROM database_backups ORDER BY id DESC LIMIT 1",
                    (rs, rowNum) -> {
                        java.sql.Timestamp ts = rs.getTimestamp("backup_time");
                        String timeStr = ts != null 
                                ? ts.toLocalDateTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                : "N/A";
                        
                        java.sql.Timestamp minioTs = rs.getTimestamp("minio_sync_time");
                        String minioTimeStr = minioTs != null
                                ? minioTs.toLocalDateTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                : "N/A";

                        java.sql.Timestamp ncTs = rs.getTimestamp("nextcloud_sync_time");
                        String ncTimeStr = ncTs != null
                                ? ncTs.toLocalDateTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                : "N/A";

                        String minioStat = rs.getString("minio_status");
                        String ncStat = rs.getString("nextcloud_status");
                        String statusVal = rs.getString("status");

                        // Estimated next backup time (24h after last backup)
                        String nextTimeStr = "N/A";
                        if (ts != null) {
                            nextTimeStr = ts.toLocalDateTime().plusDays(1).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                        }

                        return new BackupInfo(
                                timeStr,
                                statusVal,
                                statusVal,
                                rs.getBoolean("success"),
                                minioStat != null ? minioStat : "UNKNOWN",
                                minioTimeStr,
                                ncStat != null ? ncStat : "UNKNOWN",
                                ncTimeStr,
                                nextTimeStr,
                                dbStats,
                                codeStats,
                                dockerStats
                        );
                    }
            );
        } catch (Exception e) {
            log.debug("No backup record found in database_backups or table does not exist: {}", e.getMessage());
        }

        // Fallback: No backup log found – return placeholder
        return new BackupInfo("N/A", "NOT_CONFIGURED", "NOT_CONFIGURED", false, "UNKNOWN", "N/A", "UNKNOWN", "N/A", "N/A", dbStats, codeStats, dockerStats);
    }

    // --- DTO Records ---

    public record DevOpsStatsResponse(
            GitInfo git,
            MigrationInfo lastMigration,
            ComputeInfo compute,
            BackupInfo lastBackup,
            GithubInfo github
    ) {}

    public record GitInfo(
            String branch,
            String commitShort,
            String commitFull,
            String commitMessage,
            String commitTime,
            String commitAuthor
    ) {}

    public record MigrationInfo(
            String version,
            String description,
            String installedOn,
            boolean success
    ) {}

    public record ComputeInfo(
            String tier,
            int cpuCores,
            long maxMemoryMb,
            long usedMemoryMb,
            long totalMemoryMb,
            String javaVersion,
            String osInfo,
            long heapUsedMb,
            long nonHeapUsedMb,
            long heapMaxMb
    ) {}

    public record BackupInfo(
            String lastBackupTime,
            String status,
            String lastStatus,
            boolean success,
            String minioStatus,
            String minioSyncTime,
            String nextcloudStatus,
            String nextcloudSyncTime,
            String nextBackupTime,
            BucketStats dbBackups,
            BucketStats codeBackups,
            BucketStats dockerBackups
    ) {}

    public record BucketStats(
            String name,
            long totalFiles,
            long totalSize
    ) {}

    public record GithubInfo(
            String frontendRepo,
            String backendRepo
    ) {}
}
