package com.company.ftthgis.api.system;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.Properties;

/**
 * REST Controller to expose DevOps-related statistics for the admin dashboard.
 * Provides information about: Git branch/commit, Flyway migration status,
 * server compute resources, and last database backup timestamp.
 */
@RestController
@RequestMapping("/api/v1/system/devops-stats")
@RequiredArgsConstructor
@Slf4j
@PreAuthorize("hasRole('super_admin')")
public class DevOpsStatsController {

    private final JdbcTemplate jdbcTemplate;

    @Value("${app.devops.github.frontend-repo:https://github.com/user/front_springboot_ftth_gis}")
    private String frontendRepoUrl;

    @Value("${app.devops.github.backend-repo:https://github.com/user/back_springboot_ftth_gis}")
    private String backendRepoUrl;

    @Value("${app.devops.backup.log-path:/var/backups/postgresql/last_backup.log}")
    private String backupLogPath;

    @GetMapping
    public ResponseEntity<DevOpsStatsResponse> getDevOpsStats() {
        try {
            // 1. Load Git properties (generated by git-commit-id-maven-plugin at compile time)
            GitInfo gitInfo = loadGitInfo();

            // 2. Query Flyway migration history for the latest successful migration
            MigrationInfo migrationInfo = loadMigrationInfo();

            // 3. Gather compute resources from JVM runtime
            ComputeInfo computeInfo = loadComputeInfo();

            // 4. Determine last backup timestamp
            BackupInfo backupInfo = loadBackupInfo();

            // 5. Check database settings for custom GitHub repository
            String dbGithubSetting = getGithubRepoFromSettings();
            String repo = parseRepoFromJson(dbGithubSetting);
            String frontendUrl = (repo != null && !repo.isEmpty()) ? "https://github.com/" + repo : frontendRepoUrl;
            String backendUrl = (repo != null && !repo.isEmpty()) ? "https://github.com/" + repo : backendRepoUrl;

            DevOpsStatsResponse response = new DevOpsStatsResponse(
                    gitInfo,
                    migrationInfo,
                    computeInfo,
                    backupInfo,
                    new GithubInfo(frontendUrl, backendUrl)
            );

            return ResponseEntity.ok(response);
        } catch (Exception e) {
            log.error("Failed to load DevOps stats: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError().build();
        }
    }

    private String getGithubRepoFromSettings() {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT config_value FROM system_settings WHERE config_key = 'github_integration'",
                    String.class
            );
        } catch (Exception e) {
            return null;
        }
    }

    private String parseRepoFromJson(String json) {
        if (json == null || !json.contains("\"repo\":\"")) {
            return null;
        }
        try {
            int start = json.indexOf("\"repo\":\"") + 8;
            int end = json.indexOf("\"", start);
            if (start > 7 && end > start) {
                return json.substring(start, end);
            }
        } catch (Exception e) {
            // ignore
        }
        return null;
    }

    /**
     * Reads git.properties from classpath. This file is generated by
     * git-commit-id-maven-plugin during the Maven build phase.
     */
    private GitInfo loadGitInfo() {
        Properties gitProps = new Properties();
        try (InputStream is = getClass().getClassLoader().getResourceAsStream("git.properties")) {
            if (is != null) {
                gitProps.load(is);
            } else {
                log.warn("git.properties not found on classpath. Git info will use fallback values.");
            }
        } catch (IOException e) {
            log.warn("Could not read git.properties: {}", e.getMessage());
        }

        return new GitInfo(
                gitProps.getProperty("git.branch", "main"),
                gitProps.getProperty("git.commit.id.abbrev", "unknown"),
                gitProps.getProperty("git.commit.id.full", "unknown"),
                gitProps.getProperty("git.commit.message.short", "N/A"),
                gitProps.getProperty("git.commit.time", "N/A"),
                gitProps.getProperty("git.commit.user.name", "N/A")
        );
    }

    /**
     * Queries the Flyway schema history table for the most recently applied migration.
     * Uses parameterized query via JdbcTemplate (safe from SQL injection).
     */
    private MigrationInfo loadMigrationInfo() {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT version, description, installed_on, success " +
                    "FROM flyway_schema_history " +
                    "WHERE success = true " +
                    "ORDER BY installed_rank DESC LIMIT 1",
                    (rs, rowNum) -> new MigrationInfo(
                            rs.getString("version"),
                            rs.getString("description"),
                            rs.getTimestamp("installed_on") != null
                                    ? rs.getTimestamp("installed_on").toLocalDateTime()
                                            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                    : "N/A",
                            rs.getBoolean("success")
                    )
            );
        } catch (Exception e) {
            log.warn("Could not query flyway_schema_history: {}", e.getMessage());
            return new MigrationInfo("N/A", "Unable to retrieve", "N/A", false);
        }
    }

    /**
     * Reads JVM runtime information for compute resource monitoring.
     * This avoids needing external system libraries.
     */
    private ComputeInfo loadComputeInfo() {
        Runtime runtime = Runtime.getRuntime();
        int cpuCores = runtime.availableProcessors();
        long maxMemoryMb = runtime.maxMemory() / (1024 * 1024);
        long usedMemoryMb = (runtime.totalMemory() - runtime.freeMemory()) / (1024 * 1024);
        long totalMemoryMb = runtime.totalMemory() / (1024 * 1024);

        // Determine VM tier label based on CPU/RAM
        String tier;
        if (cpuCores <= 1 && maxMemoryMb <= 1024) {
            tier = "NANO";
        } else if (cpuCores <= 2 && maxMemoryMb <= 2048) {
            tier = "MICRO";
        } else if (cpuCores <= 2 && maxMemoryMb <= 4096) {
            tier = "SMALL";
        } else if (cpuCores <= 4 && maxMemoryMb <= 8192) {
            tier = "MEDIUM";
        } else {
            tier = "LARGE";
        }

        return new ComputeInfo(
                tier,
                cpuCores,
                maxMemoryMb,
                usedMemoryMb,
                totalMemoryMb,
                System.getProperty("java.version"),
                System.getProperty("os.name") + " " + System.getProperty("os.arch")
        );
    }

    /**
     * Attempts to read the last backup timestamp from a log file.
     * If the log file is not available, returns a fallback indicating backup status is unknown.
     */
    private BackupInfo loadBackupInfo() {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT backup_time, status, success FROM database_backups ORDER BY id DESC LIMIT 1",
                    (rs, rowNum) -> {
                        java.sql.Timestamp ts = rs.getTimestamp("backup_time");
                        String timeStr = ts != null 
                                ? ts.toLocalDateTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                                : "N/A";
                        return new BackupInfo(
                                timeStr,
                                rs.getString("status"),
                                rs.getBoolean("success")
                        );
                    }
            );
        } catch (Exception e) {
            log.debug("No backup record found in database_backups or table does not exist: {}", e.getMessage());
        }

        // Fallback: No backup log found – return placeholder
        return new BackupInfo("N/A", "NOT_CONFIGURED", false);
    }

    // --- DTO Records ---

    public record DevOpsStatsResponse(
            GitInfo git,
            MigrationInfo lastMigration,
            ComputeInfo compute,
            BackupInfo lastBackup,
            GithubInfo github
    ) {}

    public record GitInfo(
            String branch,
            String commitShort,
            String commitFull,
            String commitMessage,
            String commitTime,
            String commitAuthor
    ) {}

    public record MigrationInfo(
            String version,
            String description,
            String installedOn,
            boolean success
    ) {}

    public record ComputeInfo(
            String tier,
            int cpuCores,
            long maxMemoryMb,
            long usedMemoryMb,
            long totalMemoryMb,
            String javaVersion,
            String osInfo
    ) {}

    public record BackupInfo(
            String lastBackupTime,
            String status,
            boolean success
    ) {}

    public record GithubInfo(
            String frontendRepo,
            String backendRepo
    ) {}
}
